name: CI
on:
  pull_request:
    branches: [main]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: lint code
        run: |
          pip install -r requirements.txt
          make lint

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t keras_resnet_rs . --build-arg IMAGE_TAG=latest
      - name: Run
        run: docker run --rm keras_resnet_rs python -c "from resnet_rs import ResNetRS50"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tensorflow-version: [ 2.4, 2.5, 2.6, 2.7 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies (TF version ${{ matrix.tensorflow-version }})
        run: |
          python -m pip install --upgrade pip
          python -m pip install tensorflow~=${{matrix.tensorflow-version}}.0
          pip install -e .
      - name: Run tests
        run: make test
