name: CI
on:
  pull_request:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: lint code
        run: |
          pip install -r requirements.txt
          make lint

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t keras_resnet_rs . --build-arg IMAGE_TAG=latest
      - name: Run
        run: docker run --rm keras_resnet_rs python -c "from resnet_rs import ResNetRS50"

  pip-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install
        run: |
          pip install --upgrade pip
          pip install tensorflow-cpu
          pip install git+https://github.com/sebastian-sz/resnet-rs-keras@$GITHUB_HEAD_REF
      - name: Import
        run: python -c "from resnet_rs import ResNetRS50"

  check_output_consistency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install tensorflow
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow-cpu
          pip install -e .
      - name: check consistency
        run: python test_resnet_rs/check_output_consistency.py

  generate_tests_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          VERSIONS=$(python .github/scripts/generate_tf_dependency_matrix.py)
          echo "::set-output name=matrix::${VERSIONS//'%'/'%25'}"

  test:
    needs: generate_tests_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tensorflow-version: ${{fromJson(needs.generate_tests_matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies (TF version ${{ matrix.tensorflow-version }})
        run: |
          python -m pip install --upgrade pip
          python -m pip install tensorflow~=${{matrix.tensorflow-version}}.0
          pip install -r test_resnet_rs/requirements.txt
          pip install -e .
      - name: Run tests
        run: make test  # Run all tests except check_output_consistency.py
